services:
  - type: web
    name: n8n
    env: docker
    dockerfilePath: ./Dockerfile
    healthCheckPath: /healthz
    envVars:
      - key: N8N_HOST
        value: n8n.onrender.com
      - key: DB_TYPE
        value: postgresdb
      - fromEnvironmentGroup: n8n-credentials
      - fromService:
          type: pserv
          name: n8n-db
          property: connectionString

  - type: pserv
    name: n8n-db
    env: postgres
    disk:
      name: n8n-data
      sizeGB: 1
